version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dns
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /app/node_modules
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:

